### ISSUE TITLE
move to ocaml-community?

### ISSUE THREAD

**Issue by c-cube** [ocaml-community/ISO8601.ml#13]
seems like this repo is relatively dead, I think it could be moved to ocaml-community (where I'd be happy to assure basic maintenance). What do you think @sagotch ?

**Comment by sagotch** [comment]
Totally agreed!

If you migrate this, note that there is a `test` branch where unit tests happen. https://github.com/sagotch/ISO8601.ml/tree/test

5 years ago, it seemed a good idea to me de clearly separate test from code with different branches...

**Comment by c-cube** [comment]
https://github.com/ocaml-community/meta/issues/33 seems like a go. Can you transfer the repo to ocaml-community?

**Comment by sagotch** [comment]
How can I do that?

I tried to transfer it to you so you can transfer it to ocaml-community but "c-cube/ISO8601.ml already exists"

**Comment by c-cube** [comment]
I just deleted my fork, can you retry? Sorry for the inconvenience :/

**Comment by c-cube** [comment]
:100:
